-- Migrate data from old to new schema Oct 2020
-- Instructions:
-- 1. After getting an ubuntu user readable copy of the latest backup in prod root, copy to local dev, e.g.
--    scp -i ~/.ssh/<prod-pem-file> ubuntu@<prod-server-name>:~/backup17.sql ~/projects/searchmysite/src/db/datamigration/
-- 2. Copy the public.tbldomains and public.tblfilters sections (no need for public.tblindexinglog)
-- 3. Copy over the COPY public.tbldomains line with the new COPY public.tblindexeddomains line to get the new table name and column names
--    and rename public.tblfilters to public.tblindexingfilters
-- 4. Copy the file to somewhere inside the container, e.g.
--    sudo cp ~/projects/searchmysite/src/db/datamigration/datamigration.sql  ~/projects/searchmysite/data/sqldata/
-- 5. Run inside container, i.e.
--    docker exec src_db_1 /bin/bash -c "psql -U postgres searchmysitedb < /var/lib/postgresql/data/datamigration.sql"
-- 6. Cleanup files:
--    sudo rm ~/projects/searchmysite/data/sqldata/datamigration.sql
--    rm ~/projects/searchmysite/src/db/datamigration/backup17.sql
-- 7. Run SQL to move pending submissions from tblindexeddomains to tblpendingdomains:
--    INSERT INTO tblPendingDomains(domain, home_page, owner_submitted, submission_method, date_domain_added, contact_email, validation_key, password) SELECT domain, home_page, owner_verified, validation_method, date_domain_added, contact_email, validation_key, password FROM tblIndexedDomains WHERE owner_verified = false
--    UPDATE tblPendingDomains SET owner_submitted = true, submission_method = 'DCV' WHERE owner_submitted = false
--    DELETE FROM tblIndexedDomains WHERE owner_verified = false
-- 8. Reindex everything and set indexing_frequency and indexing_page_limit to new default values:
--    UPDATE tblIndexedDomains SET  indexing_current_status = 'PENDING', indexing_frequency = '3.5 days', indexing_page_limit = 1000

